name: test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: check out parent
      uses: actions/checkout@v4
      with:
        repository: t2-project/microservices
        submodules: true
    - name: set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Maven verify common
      run: |
        chmod +x mvnw
        ./mvnw --projects common --also-make clean verify
