name: test
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: check out common
      uses: actions/checkout@master
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: export envs
      run: export TRAM_VERSION=${{test.TRAM_VERSION}}
    - name: verify common
      run: echo $TRAM_VERSION && mvn clean verify
