name: test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: check out common
      uses: actions/checkout@v4
    - name: set up jdk
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Maven verify common
      run: mvn clean verify
