name: test
on: push

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: check out common
      uses: actions/checkout@master
    - name: set up jdk
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: source envs
      run: . ./setenv.sh
    - name: verify common
      run: echo $TRAM_VERSION && mvn clean verify
