name: test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: set env
      run: |
         curl -o setenv.sh -- 'https://raw.githubusercontent.com/t2-project/devops/main/setenv.sh'
         vi setenv.sh -c ':%s/^export //' -c ':%s/\(.*\)#.*/\1/' -c ':%s/\s*$//g' -c ':wq' # Strip out 'export ' at the beginning, comments, and trailing whitespace
         cat setenv.sh >> $GITHUB_ENV
    - name: check out common
      uses: actions/checkout@master
    - name: set up jdk
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: verify common
      run: mvn clean verify
